baseurl = "https://romantomjak.com"
title = "Notes on programming"
pygmentsUseClasses = true
pygmentsCodeFences = true
languageCode = "en-gb"
copyright = "Copyright (c) 2018, Roman Tomjak; all rights reserved."

[params]
  author = "Roman Tomjak"
  avatar = "/images/mother-of-god.gif"
